-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local message_common = require("pb.message_common_pb")
local message_common_pb = message_common_pb
module('message_client_pb')


local TESTMESSAGE = protobuf.Descriptor();
local TESTMESSAGE_TYPE_FIELD = protobuf.FieldDescriptor();
local TESTMESSAGE_ID_FIELD = protobuf.FieldDescriptor();
local TESTMESSAGE_BUFF_FIELD = protobuf.FieldDescriptor();
local TESTMESSAGE_INFO_FIELD = protobuf.FieldDescriptor();
local TESTMESSAGE2 = protobuf.Descriptor();
local TESTMESSAGE2_TYPE_FIELD = protobuf.FieldDescriptor();
local TESTMESSAGE2_ID_FIELD = protobuf.FieldDescriptor();
local TESTMESSAGE2_BUFF_FIELD = protobuf.FieldDescriptor();
local TESTMESSAGE2_INFO_FIELD = protobuf.FieldDescriptor();


TESTMESSAGE_TYPE_FIELD.name = "type"
TESTMESSAGE_TYPE_FIELD.full_name = "pb.TestMessage.type"
TESTMESSAGE_TYPE_FIELD.number = 1
TESTMESSAGE_TYPE_FIELD.index = 0
TESTMESSAGE_TYPE_FIELD.label = 1
TESTMESSAGE_TYPE_FIELD.has_default_value = true
TESTMESSAGE_TYPE_FIELD.default_value = message_common_pb.NET_TYPE_TESTMESSAGE1
TESTMESSAGE_TYPE_FIELD.enum_type = message_common_pb.NET_TYPE
TESTMESSAGE_TYPE_FIELD.type = 14
TESTMESSAGE_TYPE_FIELD.cpp_type = 8

TESTMESSAGE_ID_FIELD.name = "id"
TESTMESSAGE_ID_FIELD.full_name = "pb.TestMessage.id"
TESTMESSAGE_ID_FIELD.number = 2
TESTMESSAGE_ID_FIELD.index = 1
TESTMESSAGE_ID_FIELD.label = 1
TESTMESSAGE_ID_FIELD.has_default_value = false
TESTMESSAGE_ID_FIELD.default_value = 0
TESTMESSAGE_ID_FIELD.type = 5
TESTMESSAGE_ID_FIELD.cpp_type = 1

TESTMESSAGE_BUFF_FIELD.name = "buff"
TESTMESSAGE_BUFF_FIELD.full_name = "pb.TestMessage.buff"
TESTMESSAGE_BUFF_FIELD.number = 3
TESTMESSAGE_BUFF_FIELD.index = 2
TESTMESSAGE_BUFF_FIELD.label = 1
TESTMESSAGE_BUFF_FIELD.has_default_value = false
TESTMESSAGE_BUFF_FIELD.default_value = ""
TESTMESSAGE_BUFF_FIELD.type = 12
TESTMESSAGE_BUFF_FIELD.cpp_type = 9

TESTMESSAGE_INFO_FIELD.name = "info"
TESTMESSAGE_INFO_FIELD.full_name = "pb.TestMessage.info"
TESTMESSAGE_INFO_FIELD.number = 4
TESTMESSAGE_INFO_FIELD.index = 3
TESTMESSAGE_INFO_FIELD.label = 1
TESTMESSAGE_INFO_FIELD.has_default_value = false
TESTMESSAGE_INFO_FIELD.default_value = nil
TESTMESSAGE_INFO_FIELD.message_type = message_common_pb.DIRINFO
TESTMESSAGE_INFO_FIELD.type = 11
TESTMESSAGE_INFO_FIELD.cpp_type = 10

TESTMESSAGE.name = "TestMessage"
TESTMESSAGE.full_name = "pb.TestMessage"
TESTMESSAGE.nested_types = {}
TESTMESSAGE.enum_types = {}
TESTMESSAGE.fields = {TESTMESSAGE_TYPE_FIELD, TESTMESSAGE_ID_FIELD, TESTMESSAGE_BUFF_FIELD, TESTMESSAGE_INFO_FIELD}
TESTMESSAGE.is_extendable = false
TESTMESSAGE.extensions = {}
TESTMESSAGE2_TYPE_FIELD.name = "type"
TESTMESSAGE2_TYPE_FIELD.full_name = "pb.TestMessage2.type"
TESTMESSAGE2_TYPE_FIELD.number = 1
TESTMESSAGE2_TYPE_FIELD.index = 0
TESTMESSAGE2_TYPE_FIELD.label = 1
TESTMESSAGE2_TYPE_FIELD.has_default_value = true
TESTMESSAGE2_TYPE_FIELD.default_value = message_common_pb.NET_TYPE_TESTMESSAGE2
TESTMESSAGE2_TYPE_FIELD.enum_type = message_common_pb.NET_TYPE
TESTMESSAGE2_TYPE_FIELD.type = 14
TESTMESSAGE2_TYPE_FIELD.cpp_type = 8

TESTMESSAGE2_ID_FIELD.name = "id"
TESTMESSAGE2_ID_FIELD.full_name = "pb.TestMessage2.id"
TESTMESSAGE2_ID_FIELD.number = 2
TESTMESSAGE2_ID_FIELD.index = 1
TESTMESSAGE2_ID_FIELD.label = 1
TESTMESSAGE2_ID_FIELD.has_default_value = false
TESTMESSAGE2_ID_FIELD.default_value = 0
TESTMESSAGE2_ID_FIELD.type = 5
TESTMESSAGE2_ID_FIELD.cpp_type = 1

TESTMESSAGE2_BUFF_FIELD.name = "buff"
TESTMESSAGE2_BUFF_FIELD.full_name = "pb.TestMessage2.buff"
TESTMESSAGE2_BUFF_FIELD.number = 3
TESTMESSAGE2_BUFF_FIELD.index = 2
TESTMESSAGE2_BUFF_FIELD.label = 1
TESTMESSAGE2_BUFF_FIELD.has_default_value = false
TESTMESSAGE2_BUFF_FIELD.default_value = ""
TESTMESSAGE2_BUFF_FIELD.type = 12
TESTMESSAGE2_BUFF_FIELD.cpp_type = 9

TESTMESSAGE2_INFO_FIELD.name = "info"
TESTMESSAGE2_INFO_FIELD.full_name = "pb.TestMessage2.info"
TESTMESSAGE2_INFO_FIELD.number = 4
TESTMESSAGE2_INFO_FIELD.index = 3
TESTMESSAGE2_INFO_FIELD.label = 1
TESTMESSAGE2_INFO_FIELD.has_default_value = false
TESTMESSAGE2_INFO_FIELD.default_value = nil
TESTMESSAGE2_INFO_FIELD.message_type = TESTMESSAGE
TESTMESSAGE2_INFO_FIELD.type = 11
TESTMESSAGE2_INFO_FIELD.cpp_type = 10

TESTMESSAGE2.name = "TestMessage2"
TESTMESSAGE2.full_name = "pb.TestMessage2"
TESTMESSAGE2.nested_types = {}
TESTMESSAGE2.enum_types = {}
TESTMESSAGE2.fields = {TESTMESSAGE2_TYPE_FIELD, TESTMESSAGE2_ID_FIELD, TESTMESSAGE2_BUFF_FIELD, TESTMESSAGE2_INFO_FIELD}
TESTMESSAGE2.is_extendable = false
TESTMESSAGE2.extensions = {}

TestMessage = protobuf.Message(TESTMESSAGE)
TestMessage2 = protobuf.Message(TESTMESSAGE2)

